"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import { AuthcontextProvider } from "./authcontext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <AuthcontextProvider>{children}</AuthcontextProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
